### ISSUE TITLE
Question on data representation.  

### ISSUE THREAD

**Issue by bobolobo** [mixmastamyk/winstats#4]
Hello again.  Sorry for the dumb question but is the data being returned by :  "winstats.get_perf_data(i, fmts='double')"
in bits or bytes?  I assume bits?   

I'm seeing some weirdness in "Virtual Bytes" measurements but it may be because "Virtual Bytes" encompasses everything dealing with the initial process and at times goes much higher than actual physical memory and that was throwing my brain off at times :)

Thanks,
Bob

**Comment by mixmastamyk** [comment]
I'm not sure.  I think the counter definitions are on the MS site.  Did the API link in the docs help?

- http://msdn.microsoft.com/en-us/library/windows/desktop/aa373214
